TESTS += modules/arch/mips/tests/mips_test.sh

EXTRA_DIST += modules/arch/mips/tests/mips_test.sh
EXTRA_DIST += modules/arch/mips/tests/mips-basic.asm
EXTRA_DIST += modules/arch/mips/tests/mips-basic.errwarn
EXTRA_DIST += modules/arch/mips/tests/mips-basic.hex
EXTRA_DIST += modules/arch/mips/tests/mips-br.asm
EXTRA_DIST += modules/arch/mips/tests/mips-br.hex
EXTRA_DIST += modules/arch/mips/tests/mips-ea-err.asm
EXTRA_DIST += modules/arch/mips/tests/mips-ea-err.errwarn
EXTRA_DIST += modules/arch/mips/tests/mips-mp22NC.asm
EXTRA_DIST += modules/arch/mips/tests/mips-mp22NC.hex
